import 'dart:io';
import 'dart:math';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/user_model.dart';
import '../services/api_service.dart';

class UserProvider with ChangeNotifier {
  User? _user;
  bool _isLoading = false;
  final ApiService _apiService = ApiService();

  User? get user => _user;
  bool get isLoading => _isLoading;

  /// Old fingerprint (model+device+brand+build-id) collided across every
  /// phone of the same model/firmware, silently locking unrelated users out
  /// of each other's accounts. Existing accounts already have this value
  /// stored server-side, so it's always tried FIRST on every login attempt
  /// (this also correctly re-matches existing users after a reinstall).
  static const _legacyDeviceIdKey = 'device_id_legacy_v1';

  /// Random per-install UUID, unique regardless of model/firmware. Only sent
  /// as a fallback when the backend confirms the legacy fingerprint collides
  /// with a genuinely different account (DEVICE_ALREADY_REGISTERED) — i.e.
  /// this is really a new signup, not an existing user's device.
  static const _installDeviceIdKey = 'device_id_install_uuid_v2';

  Future<String?> _legacyDeviceId() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      String? legacyId = prefs.getString(_legacyDeviceIdKey);
      if (legacyId == null) {
        legacyId = await _computeLegacyFingerprint();
        if (legacyId != null) {
          await prefs.setString(_legacyDeviceIdKey, legacyId);
        }
      }
      return legacyId;
    } catch (e) {
      print('Error getting device ID: $e');
    }
    return null;
  }

  static const _deviceChannel = MethodChannel('com.reward.server/device');

  /// Stable per-phone id that clearing app data or reinstalling can't reset
  /// (Android: ANDROID_ID, iOS: identifierForVendor). The backend uses it to
  /// enforce one account per phone, since both [_legacyDeviceIdKey] and
  /// [_installDeviceIdKey] can be regenerated by clearing app data.
  Future<String?> _hardwareId() async {
    try {
      if (kIsWeb) return null;
      if (Platform.isAndroid) {
        final id = await _deviceChannel.invokeMethod<String>('getAndroidId');
        // Known bogus value shared by many old/buggy devices.
        if (id == null || id.isEmpty || id == '9774d56d682e549c') return null;
        return 'a_$id';
      } else if (Platform.isIOS) {
        final id = (await DeviceInfoPlugin().iosInfo).identifierForVendor;
        return id == null ? null : 'i_$id';
      }
    } catch (e) {
      print('Error getting hardware ID: $e');
    }
    return null;
  }

  Future<String> _installDeviceId() async {
    final prefs = await SharedPreferences.getInstance();
    String? installId = prefs.getString(_installDeviceIdKey);
    if (installId == null) {
      installId = _generateUuidV4();
      await prefs.setString(_installDeviceIdKey, installId);
    }
    return installId;
  }

  Future<String?> _computeLegacyFingerprint() async {
    final DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    try {
      if (kIsWeb) {
        final WebBrowserInfo webInfo = await deviceInfo.webBrowserInfo;
        return webInfo.userAgent;
      } else if (Platform.isAndroid) {
        final AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
        final fingerprint = '${androidInfo.model}_${androidInfo.device}_${androidInfo.brand}_${androidInfo.id}';
        return fingerprint.hashCode.toString();
      } else if (Platform.isIOS) {
        final IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
        return iosInfo.identifierForVendor;
      }
    } catch (e) {
      print('Error computing legacy device fingerprint: $e');
    }
    return null;
  }

  String _generateUuidV4() {
    final rng = Random.secure();
    final bytes = List<int>.generate(16, (_) => rng.nextInt(256));
    bytes[6] = (bytes[6] & 0x0F) | 0x40; // version 4
    bytes[8] = (bytes[8] & 0x3F) | 0x80; // variant 10xx
    String hex(int start, int end) =>
        bytes.sublist(start, end).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
    return '${hex(0, 4)}-${hex(4, 6)}-${hex(6, 8)}-${hex(8, 10)}-${hex(10, 16)}';
  }

  Future<void> login(String googleId, String email, String? name, String? photoUrl, {String? referralCode}) async {
    _isLoading = true;
    notifyListeners();

    try {
      final legacyDeviceId = await _legacyDeviceId();
      final hardwareId = await _hardwareId();
      try {
        _user = await _apiService.loginWithGoogle(
          googleId: googleId,
          email: email,
          name: name,
          profilePic: photoUrl,
          deviceId: legacyDeviceId,
          hardwareId: hardwareId,
          referralCode: referralCode,
        );
      } on LoginException catch (e) {
        // The legacy fingerprint collides with a DIFFERENT existing account
        // (same model+firmware, not actually the same phone) — this is a
        // genuinely new signup, so retry once with a unique per-install id.
        if (e.errorCode == 'DEVICE_ALREADY_REGISTERED') {
          final installDeviceId = await _installDeviceId();
          _user = await _apiService.loginWithGoogle(
            googleId: googleId,
            email: email,
            name: name,
            profilePic: photoUrl,
            deviceId: installDeviceId,
            hardwareId: hardwareId,
            referralCode: referralCode,
          );
        } else {
          rethrow;
        }
      }

      // Save user ID to shared prefs for auto-login
      final prefs = await SharedPreferences.getInstance();
      if (_user != null) {
        await prefs.setInt('userId', _user!.id);
      }

    } catch (e) {
      print('Login error: $e');
      rethrow;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> loadUser() async {
     _isLoading = true;
     notifyListeners();
     try {
       final prefs = await SharedPreferences.getInstance();
       final userId = prefs.getInt('userId');
       if (userId != null) {
         _user = await _apiService.getUserProfile(userId);
       }
     } catch (e) {
       print('Load user error: $e');
     } finally {
       _isLoading = false;
       notifyListeners();
     }
  }

  Future<void> refreshUser() async {
     try {
       if (_user != null) {
         final updatedUser = await _apiService.getUserProfile(_user!.id);
         _user = updatedUser;
         notifyListeners();
       }
     } catch (e) {
       print('Refresh user error: $e');
     }
  }

  Future<void> logout() async {
    _user = null;
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove('userId');
    notifyListeners();
  }
}
